name: Restart peter.sh

on: [ workflow_dispatch ]

jobs:
  deploy:
    name: Restart
    runs-on: ubuntu-latest
    steps:
    - name: Restart the site in production
      uses: appleboy/ssh-action@v1.2.4
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        command_timeout: 10m
        script: |
          cd ~/peter.sh
          docker restart peter-sh
